"""Release notes generator.

Produces structured markdown release notes from a pipeline run.
Called automatically by run_pipeline.py, or standalone:
    uv run python scripts/generate_release_notes.py --run-id <uuid>
"""

import argparse
import json
import logging
import sys
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

OUTPUTS_DIR = Path("data/outputs")
RELEASE_NOTES_DIR = Path("docs/release_notes")


def generate_release_notes(
    run_id: str,
    run_timestamp: str,
    row_counts: dict[str, int],
    violations: dict[str, list[str]],
    flagged_deltas: int,
) -> Path:
    """Generate markdown release notes for a pipeline run.

    Args:
        run_id: UUID for the pipeline run.
        run_timestamp: ISO timestamp string (e.g. '20260220T214500').
        row_counts: Dict mapping scenario_id → output row count.
        violations: Dict mapping scenario_id → list of violation messages.
        flagged_deltas: Number of rows flagged in diff report.

    Returns:
        Path to the generated release notes markdown file.
    """
    RELEASE_NOTES_DIR.mkdir(parents=True, exist_ok=True)

    total_rows = sum(row_counts.values())
    total_violations = sum(len(v) for v in violations.values())
    status = "✅ PASS" if total_violations == 0 else f"❌ FAIL ({total_violations} violations)"

    lines = [
        f"# Release Notes — Run {run_id[:8]}",
        f"",
        f"**Timestamp:** {run_timestamp}  ",
        f"**Run ID:** `{run_id}`  ",
        f"**Status:** {status}  ",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total output rows | {total_rows:,} |",
        f"| Scenarios run | {len(row_counts)} |",
        f"| Plausibility violations | {total_violations} |",
        f"| Diff flags (>5% delta) | {flagged_deltas} |",
        f"",
        f"## Scenario Outputs",
        f"",
        f"| Scenario | Rows |",
        f"|---|---|",
    ]

    for scenario_id, count in row_counts.items():
        lines.append(f"| {scenario_id} | {count:,} |")

    lines += [
        f"",
        f"## Plausibility Checks",
        f"",
    ]

    if total_violations == 0:
        lines.append("All plausibility checks passed. ✅")
    else:
        lines.append(f"**{total_violations} violations found — do not publish until resolved.**")
        lines.append("")
        for scenario_id, msgs in violations.items():
            if msgs:
                lines.append(f"### {scenario_id}")
                for msg in msgs:
                    lines.append(f"- {msg}")

    lines += [
        f"",
        f"## Diff vs Previous Baseline",
        f"",
    ]

    if flagged_deltas == 0:
        lines.append("No output rows changed by >5% vs previous baseline. ✅")
    else:
        lines.append(
            f"**{flagged_deltas} rows changed by >5% vs previous baseline.**  "
        )
        diff_files = list(OUTPUTS_DIR.glob(f"diff_{run_timestamp}*.csv"))
        if diff_files:
            lines.append(f"See diff report: `{diff_files[0]}`")
        lines.append("")
        lines.append("> Review and approve before tagging this run as a release.")

    lines += [
        f"",
        f"---",
        f"",
        f"*Generated by `scripts/generate_release_notes.py` — ICT Electricity Demand Model*",
    ]

    notes_path = RELEASE_NOTES_DIR / f"release_{run_timestamp}_{run_id[:8]}.md"
    notes_path.write_text("\n".join(lines))
    logger.info("Release notes written to %s", notes_path)
    return notes_path


def main() -> None:
    """Standalone CLI for generating release notes from run log."""
    parser = argparse.ArgumentParser(description="Generate release notes for a pipeline run")
    parser.add_argument("--run-id", required=True, help="Run ID to generate notes for")
    args = parser.parse_args()

    run_log = OUTPUTS_DIR / "run_log.jsonl"
    if not run_log.exists():
        print(f"Run log not found at {run_log}")
        sys.exit(1)

    entry = None
    with open(run_log) as f:
        for line in f:
            record = json.loads(line)
            if record["run_id"] == args.run_id:
                entry = record
                break

    if entry is None:
        print(f"Run ID {args.run_id} not found in run log")
        sys.exit(1)

    path = generate_release_notes(
        run_id=entry["run_id"],
        run_timestamp=entry["timestamp"],
        row_counts=entry["row_counts"],
        violations={},
        flagged_deltas=entry["flagged_deltas"],
    )
    print(f"Release notes: {path}")


if __name__ == "__main__":
    main()
